const defaultFonts = [
    // Local font files
    { name: 'Abhaya Classic', url: 'fonts/AbhayaClassic-Regular.ttf', systemFont: false },
    { name: 'Abhaya Classic Pro', url: 'fonts/AbhayaClassicPro-Regular.ttf', systemFont: false },
    { name: 'Abhaya Libre', url: 'fonts/AbhayaLibre[wght].ttf', systemFont: false },
    { name: 'Aggnni', url: 'fonts/Aggnni-Regular.ttf', systemFont: false },
    { name: 'Alakamanda', url: 'fonts/Alakamanda-Regular.ttf', systemFont: false },
    { name: 'Aluvihare', url: 'fonts/Aluvihare-Regular.ttf', systemFont: false },
    { name: 'Amawathura', url: 'fonts/Amawathura-Regular.ttf', systemFont: false },
    { name: 'Arjunn', url: 'fonts/Arjunn-Regular.ttf', systemFont: false },
    { name: 'Arundathi', url: 'fonts/Arundathi-Regular.ttf', systemFont: false },
    { name: 'Bindumathee', url: 'fonts/Bindumathee-Regular.ttf', systemFont: false },
    { name: 'CC Moscow T2', url: 'fonts/CCMoscowT2.ttf', systemFont: false },
    { name: 'Dedigama DEV', url: 'fonts/DedigamaDEV-Regular.ttf', systemFont: false },
    { name: 'Derana', url: 'fonts/Derana-Regular.ttf', systemFont: false },
    { name: 'Dharanee', url: 'fonts/Dharanee-Regular.ttf', systemFont: false },
    { name: 'Galle ALPHA', url: 'fonts/GalleALPHA.ttf', systemFont: false },
    { name: 'Gandhara', url: 'fonts/Gandhara-Regular.ttf', systemFont: false },
    { name: 'Ganganee Pro DEV', url: 'fonts/GanganeeProDEV-Regular.ttf', systemFont: false },
    { name: 'Gurulugomi', url: 'fonts/Gurulugomi-Regular.ttf', systemFont: false },
    { name: 'Hopalu', url: 'fonts/Hopalu-Regular.ttf', systemFont: false },
    { name: 'Imanee', url: 'fonts/Imanee-Regular.ttf', systemFont: false },
    { name: 'Indeevari', url: 'fonts/Indeevari-Regular.ttf', systemFont: false },
    { name: 'Isiwara', url: 'fonts/Isiwara-Regular.ttf', systemFont: false },
    { name: 'Kasup', url: 'fonts/Kasup-Regular.ttf', systemFont: false },
    { name: 'Kethumathi', url: 'fonts/Kethumathi-Regular.ttf', systemFont: false },
    { name: 'Kolonbiya', url: 'fonts/Kolonbiya-Regular.ttf', systemFont: false },
    { name: 'Malithi', url: 'fonts/Malithi-Regular.ttf', systemFont: false },
    { name: 'Maname', url: 'fonts/Maname-Regular.ttf', systemFont: false },
    { name: 'Mandakini', url: 'fonts/Mandakini-Regular.ttf', systemFont: false },
    { name: 'Manike DEV', url: 'fonts/ManikeDEV-Regular.ttf', systemFont: false },
    { name: 'Manike DEV SemiBold', url: 'fonts/ManikeDEV-SemiBold.ttf', systemFont: false },
    { name: 'Nadee', url: 'fonts/Nadee-Regular.ttf', systemFont: false },
    { name: 'Noto Sans Sinhala', url: 'fonts/NotoSansSinhalaNIGHTLY-Medium.ttf', systemFont: false },
    { name: 'Rajantha', url: 'fonts/Rajantha-Regular.ttf', systemFont: false },
    { name: 'Ramya', url: 'fonts/Ramya-Regular.ttf', systemFont: false },
    { name: 'Rashmi', url: 'fonts/Rashmi-Regular.ttf', systemFont: false },
    { name: 'Sakunthala', url: 'fonts/Sakunthala-Regular.ttf', systemFont: false },
    { name: 'Samantha', url: 'fonts/Samantha-Regular.ttf', systemFont: false },
    { name: 'Sandhyanee', url: 'fonts/Sandhyanee-Regular.ttf', systemFont: false },
    { name: 'Sarani', url: 'fonts/Sarani-Regular.ttf', systemFont: false },
    { name: 'Sekara DEV', url: 'fonts/SekaraDEV-Regular.ttf', systemFont: false },
    { name: 'Singithi', url: 'fonts/Singithi-Regular.ttf', systemFont: false },
    
    // System fonts
    { name: 'Arial', url: null, systemFont: true, family: 'Arial, sans-serif' },
    { name: 'Times New Roman', url: null, systemFont: true, family: 'Times New Roman, serif' },
    { name: 'Helvetica', url: null, systemFont: true, family: 'Helvetica, sans-serif' },
    { name: 'Georgia', url: null, systemFont: true, family: 'Georgia, serif' }
];